
version: "3.5"
services:  
  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - api
    entrypoint: "npm"
    command:
      - run
      - start
    networks: 
      - proxy
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./app:/home/app
      - /home/app/node_modules
    container_name: ${APP_CONTAINER}

  api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - pgsql
    restart: on-failure
    environment:
      NODE_ENV: development
      PORT: ${API_PORT}
      HOST: 0.0.0.0
    env_file: 
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    working_dir: /home/api
    entrypoint: "npm"
    command: ["run", "start-dev"]
    networks: 
      - proxy
    volumes:
      - ./api:/home/api
      - /home/api/node_modules
    container_name: ${API_CONTAINER}
  pgsql:
    image: postgres:13.6
    restart: on-failure
    env_file:
      - .env
    volumes:
        - ./data/database:/var/lib/postgresql
    container_name: ${PG_CONTAINER}
    networks: 
      - proxy
    ports:
      - ${PG_PORT}


networks: 
  proxy:
    external: true